name: Build static and push to deploy branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build   # создаст папку out/
      - name: Push out/ to deploy branch
        run: |
          rm -rf .git
          cp -r out ../out_publish
          cd ../out_publish
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy"
          git branch -M deploy
          git remote add origin https://github.com/${{ github.repository }}.git
          git push -f origin deploy
